# Generated by Django 4.1 on 2025-01-17 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='username',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
