# Generated by Django 5.1.5 on 2025-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('BookName', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='myBook')),
                ('desc', models.TextField()),
            ],
        ),
    ]
