# Generated by Django 5.1.5 on 2025-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addb',
            name='myfile',
            field=models.FileField(upload_to='myBook/'),
        ),
    ]
