# Generated by Django 5.1.5 on 2025-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_addb_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addb',
            name='BImg',
            field=models.ImageField(default='exit', upload_to='BookImg/'),
            preserve_default=False,
        ),
    ]
