# Generated by Django 5.1.5 on 2025-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addb_bimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='addEve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('EventName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='eveImg')),
                ('desc', models.TextField()),
            ],
        ),
    ]
