# Generated by Django 5.1.5 on 2025-02-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_addeve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addeve',
            old_name='EventName',
            new_name='EventTitle',
        ),
    ]
