# Generated by Django 5.1.6 on 2025-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Romance', 'Romance'), ('Action_Adventure', 'Action & Adventure'), ('Mystery_Thriller', 'Mystery & Thriller'), ('Biographies_History', 'Biographies & History'), ('Children', 'Children'), ('Young_Adult', 'Young Adult'), ('Fantasy', 'Fantasy'), ('Historical_Fiction', 'Historical Fiction'), ('Horror', 'Horror'), ('Literary_Fiction', 'Literary Fiction'), ('Non_fiction', 'Non-fiction'), ('Science_Fiction', 'Science Fiction')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('pas', models.CharField(max_length=20)),
                ('cpas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auname', models.CharField(max_length=100)),
                ('booktitle', models.CharField(max_length=255)),
                ('pdate', models.DateField()),
                ('description', models.TextField()),
                ('img', models.ImageField(default='default.jpg', upload_to='book_images/')),
                ('myfile', models.FileField(upload_to='book_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='bookapp.genre')),
            ],
        ),
    ]
