# Generated by Django 5.1.6 on 2025-02-19 09:39

import bookapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='default', max_length=200, verbose_name=bookapp.models.Genre),
            preserve_default=False,
        ),
    ]
