# Generated by Django 5.1.6 on 2025-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
