# Generated by Django 5.1.6 on 2025-03-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
