# Generated by Django 5.1.6 on 2025-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_remove_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
