# Generated by Django 5.1.6 on 2025-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_author_bio_author_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
